//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaEmpresaPequena.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgramMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LojaEmpresaPequena.Domain.Resources.ProgramMessages", typeof(ProgramMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro inválido!.
        /// </summary>
        public static string BairroInvalido {
            get {
                return ResourceManager.GetString("BairroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto cadastrado com sucesso!.
        /// </summary>
        public static string CadastroProdSucesso {
            get {
                return ResourceManager.GetString("CadastroProdSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar obter o categoria!.
        /// </summary>
        public static string CategoriaAttempt {
            get {
                return ResourceManager.GetString("CategoriaAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep inválido!.
        /// </summary>
        public static string CepInvalido {
            get {
                return ResourceManager.GetString("CepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade inválida!.
        /// </summary>
        public static string CidadeInvalida {
            get {
                return ResourceManager.GetString("CidadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao tentar obter configurações!.
        /// </summary>
        public static string ConfigErro {
            get {
                return ResourceManager.GetString("ConfigErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf inválido!.
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email informado inválido!.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email ou senha inválidos.
        /// </summary>
        public static string EmailSenha {
            get {
                return ResourceManager.GetString("EmailSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar obter o Endereço!.
        /// </summary>
        public static string EnderecoAttempt {
            get {
                return ResourceManager.GetString("EnderecoAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado inválido!.
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar realizar a operação!.
        /// </summary>
        public static string Falha {
            get {
                return ResourceManager.GetString("Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id requisitado inválido.
        /// </summary>
        public static string IdErro {
            get {
                return ResourceManager.GetString("IdErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A marca do produto é inválida!.
        /// </summary>
        public static string MarcaProdutoInvalida {
            get {
                return ResourceManager.GetString("MarcaProdutoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro interno - Metódo não implementado.
        /// </summary>
        public static string MetodoNImplementado {
            get {
                return ResourceManager.GetString("MetodoNImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome categoria inválido!.
        /// </summary>
        public static string NomeCategoria {
            get {
                return ResourceManager.GetString("NomeCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome inválido!.
        /// </summary>
        public static string NomeInvalido {
            get {
                return ResourceManager.GetString("NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do produto é inválido!.
        /// </summary>
        public static string NomeProdutoInvalido {
            get {
                return ResourceManager.GetString("NomeProdutoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero inválido!.
        /// </summary>
        public static string NumeroInvalido {
            get {
                return ResourceManager.GetString("NumeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido inválido!.
        /// </summary>
        public static string PedidoInvalido {
            get {
                return ResourceManager.GetString("PedidoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar obter o produto!.
        /// </summary>
        public static string ProdAttempt {
            get {
                return ResourceManager.GetString("ProdAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto inválido!.
        /// </summary>
        public static string ProdutoInvalido {
            get {
                return ResourceManager.GetString("ProdutoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade Inválida!.
        /// </summary>
        public static string QuantidadeInvalida {
            get {
                return ResourceManager.GetString("QuantidadeInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua inválida!.
        /// </summary>
        public static string RuaInvalida {
            get {
                return ResourceManager.GetString("RuaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar enviar email - Falha na validação.
        /// </summary>
        public static string SendEmailErro {
            get {
                return ResourceManager.GetString("SendEmailErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha é inválida.
        /// </summary>
        public static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status do envio inválido!.
        /// </summary>
        public static string StatusEnvioInvalido {
            get {
                return ResourceManager.GetString("StatusEnvioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status do Pedido inválido!.
        /// </summary>
        public static string StatusPedidoInvalido {
            get {
                return ResourceManager.GetString("StatusPedidoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso!.
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar buscar o categorias!.
        /// </summary>
        public static string TentarBuscarCategoriaErro {
            get {
                return ResourceManager.GetString("TentarBuscarCategoriaErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar buscar o endereços!.
        /// </summary>
        public static string TentarBuscarEnderecoErro {
            get {
                return ResourceManager.GetString("TentarBuscarEnderecoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar buscar o produtos!.
        /// </summary>
        public static string TentarBuscarProdErro {
            get {
                return ResourceManager.GetString("TentarBuscarProdErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo pagamento inválido!.
        /// </summary>
        public static string TipoPagamentoInvalido {
            get {
                return ResourceManager.GetString("TipoPagamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Url informada é inválida!.
        /// </summary>
        public static string UrlInvalida {
            get {
                return ResourceManager.GetString("UrlInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido (Nulo)!.
        /// </summary>
        public static string UsuarioNulo {
            get {
                return ResourceManager.GetString("UsuarioNulo", resourceCulture);
            }
        }
    }
}
